{% set name = "hiredis" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 105596aad9249634361815c574351f1bd50455dc23b537c2940066c4a9dea685

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  skip: true  # [py<38]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - hiredis
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/redis/hiredis-py
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python wrapper for hiredis
  description: |
    Python extension that wraps protocol parsing code in hiredis.
    It primarily speeds up parsing of multi bulk replies.
  dev_url: https://github.com/redis/hiredis-py
  doc_url: https://github.com/redis/hiredis-py

extra:
  recipe-maintainers:
    - kwilcox
    - mariusvniekerk
