{% set version = "1.0.1" %}

package:
    name: hiredis
    version: {{ version }}

source:
    url: https://pypi.python.org/packages/source/h/hiredis/hiredis-{{ version }}.tar.gz
    sha256: aa59dd63bb3f736de4fc2d080114429d5d369dfb3265f771778e8349d67a97a4

build:
    number: 0
    script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - python
        - pip
    run:
        - python

test:
    imports:
        - hiredis

about:
    home: https://github.com/redis/hiredis-py
    license: BSD-3-Clause
    license_file: COPYING
    summary: Python wrapper for hiredis

extra:
    recipe-maintainers:
        - kwilcox
        - mariusvniekerk
