{% set version = "1.0.0" %}

package:
    name: hiredis
    version: {{ version }}

source:
    fn: hiredis-{{ version }}.tar.gz
    url: https://pypi.python.org/packages/source/h/hiredis/hiredis-{{ version }}.tar.gz
    md5: 46bc0d51bda994611bae77c044b1398b

build:
    number: 0
    script: python -m pip install . --ignore-installed --no-deps -vv

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - "{{ compiler('c') }}"
    host:
        - python
        - pip
    run:
        - python

test:
    imports:
        - hiredis

about:
    home: https://github.com/redis/hiredis-py
    license: BSD
    summary: Python wrapper for hiredis

extra:
    recipe-maintainers:
        - kwilcox
        - mariusvniekerk
