{% set name = "hiredis" %}
{% set version = "2.0.0" %}
{% set checksum = "81d6d8e39695f2c37954d1011c0480ef7cf444d4e3ae24bc5e89ee5de360139a" %}
{% set build = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name|lower }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: {{ checksum }}

build:
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - hiredis

about:
  home: https://github.com/redis/hiredis-py
  dev_url: https://github.com/redis/hiredis-py
  doc_url: https://github.com/redis/hiredis-py
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: Python wrapper for hiredis

extra:
  recipe-maintainers:
    - kwilcox
    - mariusvniekerk
