travis:
  secure:
    BINSTAR_TOKEN: soBcZKmG3Km/CsdaKaHWJG4cNKuwEv8mFNCrcOXWmAqtTMOZ312HfclF5Xrct/4TVQxxbddKbftyhdipadt58u81PQlnCSfeb7P1j1ziApu1eB4uAamYN+HpspPALzajtPUzLwCVWO+Il4CK4hdLnea21NgYpr04MfJZUM3kHaLVWGR3LEE041PHRQ3EfxX0RpPID36rYdPcSlBr5Zaf0J679WtBkJ35LrIGqvEX30X4Z7rAOuMx8w3RDAPKjO5D4Ex84BQUqKdiwNYkZzKGRos6c6lQQl5tFZZ5EpQb/p1788PF+js+Spq9MenA/ZcqUZjnWY2jrXxUxyUZ5A4uLRHPZU7yTOXyKqN9eb7bJK73NAWjr8XnocjDFbo3UI0Fc0oUE19WJieJlV1QNYUAZio1rrcmPrTEK/kJ/MWfF9djjlnybO+Gi+rAxcWLoHmca5xWNRa8PMoUcsgvnFsuSbanGN1HXWYfN+3mFn1DwbvGxiWpxhllY0mse1PlNA1Lw7qyeCqoxOA1In2Xn2wwDS3ZZpQbj1pA5AnBZMdSG7iC/d7b5Irl1y2eEN2YgptbvZDWPgV7j6f5MnoF1R26WACRWAlkXnY9YinPawgubogFzMWbueBAP/YKnwg1D72eZ9+A+UddWKhIkZfYgsPab1rEtqWdwl8E8loz5w3syLo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
