travis:
  secure:
    BINSTAR_TOKEN: GX0/IoP2xinW+EgER+UTu3vuhmbLQhSj39hWE2BXdRts0w8HRFBAZpkVGVuZ7qanam14KQQpS1qME18JmZvqndO6/HqD9OXAIVqMDfyx1EwrkuybmqgnAHocbQK4y9tdvkSBfoADNwa0oZtsyRpkA0X+YYNKYIi6YOgU0RBEk3TcgI8qKXGTh/ZBdjpfUTJZ67TVA/5EncaDjUywQ5Xu25/q8O+GMwdTx09nfIwXxecLT7aTu9a10lt+HQ/vRSHD3vDO97oelAtvXJv1AV5GU4f1wZ4rXpN7j3yxuuGeORV2ziN8iURkD75IeZ1a44YcKCNz4ydyTRKP3W1z2ClWJa933sln4CasbMPcDq8nd+FMnBg5tzG4dCiRq4qLuQ0AmYHXZFnz0ZOe7NIPhp5dtXAzlb2fEGVEZiT/NHFm46KN/SO2sARFukUP3WTxF6VL6IAvVblg72c2uH9A1jN96KCisZBNBwORrvucfa9Pgf/eZigKJJbKic9Nf5ZeTv6gdtOh050/fxEszebOjUMPUocKZE0W7I03KgloO+wijvpEtvy807lUjlqA+pCXi4fpL8gNNvelMgfbIUeh8TDUiTAoD1i7NBRYkD9TYXiLxy1mP43JaNO+i/frdmXpp4iZnnSOBhVhCF379RRrqJFyuQ+3KTCGSLIoNNNwE069HLc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
